version: '3.8'

services:
  app:
    container_name: rest-app
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - mongo
    volumes:
      - app:/usr/src/app/
    environment:
      - DB_PASSWORD=1245emer
    networks:
      - cloud

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

volumes:
  app:
  mongo:

networks:
  cloud:
    driver: bridge
