port: "8080"

http:
  port: 8080
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

mongo:
    databaseName: gorest

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h
  verificationCodeLength: 8